#include "help.h"
void help_switches(int full);
void version(FILE * out) {
    fprintf(out, "Android Debug Bridge version %d.%d.%d\n",
         ADB_VERSION_MAJOR, ADB_VERSION_MINOR, ADB_SERVER_VERSION);
}
void fullversion(FILE * out) {
    fprintf(out, "Android Debug Bridge Extended version %d.%d.%d.%d\n",
         ADB_VERSION_MAJOR, ADB_VERSION_MINOR, ADB_SERVER_VERSION,ADB_EXTENDED_VERSION);

}
void help_reboot(int full)
{
       if(full) 
                fprintf(stderr,

                        "  adb [reboot] <[bootloader|recovery]>         - reboots the device, optionally into the bootloader or recovery program\n"
                        "                                                 the reboot keyword is optional\n"
                        "  adb reboot-bootloader                        - reboots the device into the bootloader\n");
        else
                fprintf(stderr,
                        "  adb reboot [bootloader|recovery]            - reboots the device, optionally into the bootloader or recovery program\n"
                        "  adb reboot-bootloader                       - reboots the device into the bootloader\n");
}
void help_switches(int full)
{
        fprintf(stderr,
                        " -d                                            - directs command to the only connected USB device\n"
                        "                                                 returns an error if more than one USB device is present.\n"
                        " -e                                            - directs command to the only running emulator.\n"
                        "                                                 returns an error if more than one emulator is running.\n"
                        " -s <serial number>                            - directs command to the USB device or emulator with\n"
                        "                                                 the given serial number. Overrides ANDROID_SERIAL\n"
                        "                                                 environment variable.\n"
                        " -p <product name or path>                     - simple product name like 'sooner', or\n"
                        "                                                 a relative/absolute path to a product\n"
                        "                                                 out directory like 'out/target/product/sooner'.\n"
                        "                                                 If -p is not specified, the ANDROID_PRODUCT_OUT\n"
                        "                                                 environment variable is used, which must\n"
                        "                                                 be an absolute path.\n");
        if(full) 
                fprintf(stderr,
                        " -i <device index>                             - directs command to the device or emulator with\n"
                        "                                                 the given index number. The index number is defined\n"
                        "                                                 by the order in which the devices were connected.\n"
                        "                                                 Overrides ANDROID_INDEX environment variable\n");

        
}
void help_adb_commands(int full)
{
        
        if(full) 
                fprintf(stderr,
                        " devices | dev                                 - list all connected devices. using dev will\n"
                        "                                                 list all connected devices as an numbered list\n"
                        "                                                 The device index can be used with the -i option\n"
                        " connect | conn  <host>[:<port>]               - connect to a device via TCP/IP\n"
                        "                                                 Port 5555 is used by default if no port number is specified.\n"
                        " disconnect | discon [<host>[:<port>]]         - disconnect from a TCP/IP device.\n"
                        "                                                 Port 5555 is used by default if no port number is specified.\n"
                        "                                                 Using this command with no additional arguments\n"
                        "                                                 will disconnect from all connected TCP/IP devices.\n"
                        "\n" );
        else
                fprintf(stderr,
                        " devices                                       - list all connected devices\n"
                        " connect <host>[:<port>]                       - connect to a device via TCP/IP\n"
                        "                                                 Port 5555 is used by default if no port number is specified.\n"
                        " disconnect [<host>[:<port>]]                  - disconnect from a TCP/IP device.\n"
                        "                                                 Port 5555 is used by default if no port number is specified.\n"
                        "                                                 Using this command with no additional arguments\n"
                        "                                                 will disconnect from all connected TCP/IP devices.\n"
                        "\n" );

}
void help_sync_commands(int full)
{
        if(full) 
                fprintf(stderr,
                        "  adb push | pu <local> <remote>               - copy file/dir to device. If no remote\n"
                        "                                                 directory is specified then the root (\"/\")\n"
                        "                                                 direcory is used\n"                                       
                        "  adb pull | pl <remote> [<local>]             - copy file/dir from device. If no local\n"
                        "                                                 file is specified then the current\n"
                        "                                                 working direcory is used\n"        
                        "  adb sync [ <directory> ]                     - copy host->device only if changed\n"
                        "                                                 (-l means list but don't copy)\n"
                        "                                                 (see 'sync notes')\n"
                        "  adb shell | sh                               - run remote shell interactively\n"
                        "  adb shell | sh <command>                     - run remote shell command\n"
                        "  adb emu <command>                            - run emulator console command\n");
        else
                fprintf(stderr,
                        "  adb push <local> <remote>                    - copy file/dir to device\n"
                        "  adb pull <remote> [<local>]                  - copy file/dir from device\n"
                        "  adb sync [ <directory> ]                     - copy host->device only if changed\n"
                        "                                                 (-l means list but don't copy)\n"
                        "                                                 (see 'adb help all')\n"
                        "  adb shell                                    - run remote shell interactively\n"
                        "  adb shell <command>                          - run remote shell command\n"
                        "  adb emu <command>                            - run emulator console command\n");
        
}

void help_input(int full)
{
        if(full)
                fprintf(stderr,"input commands:\n"
                "  - You can send keyevents by name to a connected device simply by running\n"
                "       adb <keycode_name>\n"
                "  - This is the equivalent of adb shell input keyevent <keyevent code>\n"
                "    All keyevents begin with the KEYCODE prefix. Some select keyevents have\n"
                "    short versions, for a full list enter\n"
                "       adb help keycodes\n" ) ;
  
}
void help_logcat(int full)
{
        if(full) 
                fprintf(stderr,
                        "  adb logcat | lc [ <filter-spec> ]            - View device log\n"
                        "  adb longcat [ <filter-spec> ]                - View verbose device log. Events are tagged\n"
                        "                                                 date and time\n"
                        "  adb logcat-all | lca [ <filter-spec> ]       - View all device logs. This is the equivalent\n"
                        "                                                 adb logcat -b radio -b system -b events -b main\n"
                        "  adb logcat-main | lcm [ <filter-spec> ]      - View device main log only\n"
                        "  adb logcat-radio | lcr [ <filter-spec> ]     - View device radio log only\n"
                        "  adb logcat-events | lce [ <filter-spec> ]    - View device events log\n"
                        "  adb logcat-system | lcs [ <filter-spec> ]    - View device syetem log only\n"
                        "  adb logcat-help | lch                        - View help information for logcat command\n"
                        "  adb dmesg                                    - Print the kernel ring buffer. This is the equivalent\n"
                        "                                                 adb shell dmesg\n"
                );
        else
                fprintf(stderr,
                        "  adb logcat [ <filter-spec> ]                 - View device log\n"
                );
}
void help_enviroment_variables(int full)
{
        fprintf(stderr,"\n"
                "environmental variables:\n" 
                "  ADB_TRACE                                    - Print debug information. A comma separated list of the following values\n"
                "                                                 1 or all, adb, sockets, packets, rwx, usb, sync, sysdeps, transport, jdwp\n"
                "  ANDROID_SERIAL                               - The serial number to connect to. -s takes priority over this if given.\n"
                "  ANDROID_LOG_TAGS                             - When used with the logcat option, only these debug tags are printed.\n");

        if(full) 
                fprintf(stderr,
                        "  ANDROID_INDEX                                - The index number to connect to. -i takes priority over this if given.\n");
                
                        
}
void help_help(int full)
{
        if(full) 
                fprintf(stderr,
                        "  adb help                                     - show short help message\n"
                        "  adb help all                                 - show this help message\n"
                        "  adb version | ver [ full ]                   - show version number. version full will print the\n"
                        "                                                 extended version number\n"
                );
        else                  
                fprintf(stderr,      
                        "  adb help                                     - show this help message\n"
                        "  adb help all                                 - show full extended version help message\n"
                        "  adb version                                  - show version num\n");


}
void help_main(int full)
{
    fprintf(stderr,"\n");
    help_switches(full);
    help_adb_commands(full);
    fprintf(stderr,"device commands:\n");
    help_sync_commands(full);
    help_logcat(full);
    fprintf(stderr,
                        "  adb forward <local> <remote>                 - forward socket connections\n"
                        "                                                 forward specs are one of: \n"
                        "                                                 tcp:<port>\n"
                        "                                                 localabstract:<unix domain socket name>\n"
                        "                                                 localreserved:<unix domain socket name>\n"
                        "                                                 localfilesystem:<unix domain socket name>\n"
                        "                                                 dev:<character device name>\n"
                        "                                                 jdwp:<process pid> (remote only)\n"
                        "  adb jdwp                                     - list PIDs of processes hosting a JDWP transport\n"
                        "  adb install [-l] [-r] [-s] [--algo <algorithm name> --key <hex-encoded key> --iv <hex-encoded iv>] <file>\n"
                        "                                               - push this package file to the device and install it\n"
                        "                                                 ('-l' means forward-lock the app)\n"
                        "                                                 ('-r' means reinstall the app, keeping its data)\n"
                        "                                                 ('-s' means install on SD card instead of internal storage)\n"
                        "                                                 ('--algo', '--key', and '--iv' mean the file is encrypted already)\n"
                        "  adb uninstall [-k] <package> - remove this app package from the device\n"
                        "                                                 ('-k' means keep the data and cache directories)\n"
                        "  adb bugreport                                - return all information from the device\n"
                        "                                                 that should be included in a bug report.\n"
                        "\n"
                        "  adb backup [-f <file>] [-apk|-noapk] [-shared|-noshared] [-all] [-system|-nosystem] [<packages...>]\n"
                        "                                               - write an archive of the device's data to <file>.\n"
                        "                                                 If no -f option is supplied then the data is written\n"
                        "                                                 to \"backup.ab\" in the current directory.\n"
                        "                                                 (-apk|-noapk enable/disable backup of the .apks themselves\n"
                        "                                                 in the archive; the default is noapk.)\n"
                        "                                                 (-shared|-noshared enable/disable backup of the device's\n"
                        "                                                 shared storage / SD card contents; the default is noshared.)\n"
                        "                                                 (-all means to back up all installed applications)\n"
                        "                                                 (-system|-nosystem toggles whether -all automatically includes\n"
                        "                                                   system applications; the default is to include system apps)\n"
                        "                                                 (<packages...> is the list of applications to be backed up.  If\n"
                        "                                                  the -all or -shared flags are passed, then the package\n"
                        "                                                  list is optional.  Applications explicitly given on the\n"
                        "                                                  command line will be included even if -nosystem would\n"
                        "                                                  ordinarily cause them to be omitted.)\n"
                        "\n"
                        "  adb restore <file>                           - restore device contents from the <file> backup archive\n"
                        "\n");
                        help_help(full);
                        fprintf(stderr,"\n"
                        "scripting:\n"
                        "  adb wait-for-device                          - block until device is online\n"
                        "  adb start-server                             - ensure that there is a server running\n"
                        "  adb kill-server                              - kill the server if it is running\n"
                        "  adb get-state                                - prints: offline | bootloader | device\n"
                        "  adb get-serialno                             - prints: <serial-number>\n"
                        "  adb status-window                            - continuously print device status for a specified device\n"
                        "  adb remount                                  - remounts the /system partition on the device read-write\n");
                        help_reboot(full);
                        fprintf(stderr,
                        "  adb root                                     - restarts the adbd daemon with root permissions\n"
                        "  adb usb                                      - restarts the adbd daemon listening on USB\n"
                        "  adb tcpip <port>                             - restarts the adbd daemon listening on TCP on the specified port\n");
                        if(full)fprintf(stderr,"\n");                      
                        fprintf(stderr,"networking:\n"
                        "  adb ppp <tty> [parameters]   - Run PPP over USB.\n"
                        " Note: you should not automatically start a PPP connection.\n"
                        " <tty> refers to the tty for PPP stream. Eg. dev:/dev/omap_csmi_tty1\n"
                        " [parameters] - Eg. defaultroute debug dump local notty usepeerdns\n"
                        "\n"
                        "adb sync notes: adb sync [ <directory> ]\n"
                        "  <localdir> can be interpreted in several ways:\n"
                        "\n"
                        "  - If <directory> is not specified, both /system and /data partitions will be updated.\n"
                        "\n"
                        "  - If it is \"system\" or \"data\", only the corresponding partition\n"
                        "    is updated.\n"
                        "\n"
                        );
                        help_input(full);
                        help_enviroment_variables(full);
}
void help_all()
{
   fullversion(stderr);
   help_main(1);

}
void help()
{
    version(stderr);
    help_main(0);
}
int usage()
{
    help();
    return 1;
}


void help_keycodes(){
        fprintf(stderr,"\nKey code constant: Unknown Key code. \n"
                        "KEYCODE_UNKNOWN=0\n"
                        "Key code constant: Soft Left Key.\n"
                        "Usually situated below the display on phones and used as a multi-function\n"
                        "feature Key for selecting a software defined function shown on the bottom left\n"
                        "of the display. \n"
                        "KEYCODE_SOFT_LEFT=1\n"
                        "lft=1\n"
                        "Key code constant: Soft Right Key.\n"
                        "Usually situated below the display on phones and used as a multi-function\n"
                        "feature Key for selecting a software defined function shown on the bottom right\n"
                        "of the display. \n"
                        "KEYCODE_SOFT_RIGHT\n" "2\n"
                        "rgt=2\n"
                        "Key code constant: Home Key.\n" 
                        "This Key is handled by the framework and is never delivered to applications. \n"
                        "KEYCODE_HOME=3\n"
                        "home=3\n"
                        "hm=3\n"
                        "Key code constant: Back Key.\n"
                        "KEYCODE_BACK=4\n"
                        "back=4=bk=4\n"
                        "Key code constant: Call Key.\n"
                        "KEYCODE_CALL=5\n"
                        "call=5\n"
                        "Key code constant: End Call Key.\n"
                        "KEYCODE_ENDCALL=6\n"
                        "endcall=6=hangup=6\n"
                        "Key code constant: '0' Key.\n"
                        "KEYCODE_0=7\n"
                        "0=7\n"
                        "Key code constant: '1' Key.\n"
                        "KEYCODE_1=8\n"
                        "1=8\n"
                        "Key code constant: '2' Key.\n"
                        "KEYCODE_2=9\n"
                        "Key code constant: '3' Key.\n"
                        "KEYCODE_3=10\n"
                        "Key code constant: '4' Key.\n"
                        "KEYCODE_4=11\n"
                        "Key code constant: '5' Key.\n"
                        "KEYCODE_5=12\n"
                        "Key code constant: '6' Key.\n"
                        "KEYCODE_6=13\n"
                        "Key code constant: '7' Key.\n"
                        "KEYCODE_7=14\n"
                        "Key code constant: '8' Key.\n"
                        "KEYCODE_8=15\n"
                        "Key code constant: '9' Key.\n"
                        "KEYCODE_9=16\n"
                        "Key code constant: '*' Key.\n"
                        "KEYCODE_STAR=17\n"
                        "Key code constant: '#' Key.\n"
                        "KEYCODE_POUND=18\n"
                        "Key code constant: Directional Pad Up Key.\n"
                        "May also be synthesized from trackball motions. \n"
                        "KEYCODE_DPAD_UP=19\n"
                        "dup=19=up=19\n"
                        "Key code constant: Directional Pad Down Key.\n"
                        "May also be synthesized from trackball motions. \n"
                        "KEYCODE_DPAD_DOWN=20\n"
                        "down=20\n"
                        "Key code constant: Directional Pad Left Key.\n"
                        "May also be synthesized from trackball motions. \n"
                        "KEYCODE_DPAD_LEFT=21\n"
                        "left=21\n"
                        "Key code constant: Directional Pad Right Key.\n"
                        "May also be synthesized from trackball motions. \n"
                        "KEYCODE_DPAD_RIGHT\n" "22\n"
                        "right=22\n"
                        "Key code constant: Directional Pad Center Key.\n"
                        "May also be synthesized from trackball motions. \n"
                        "KEYCODE_DPAD_CENTER=23\n"
                        "center=23\n"
                        "Key code constant: Volume Up Key.\n"
                        "Adjusts the speaker volume up. \n"
                        "KEYCODE_VOLUME_UP=24\n"
                        "volup=24\n"
                        "Key code constant: Volume Down Key.\n"
                        "Adjusts the speaker volume down. \n"
                        "KEYCODE_VOLUME_DOWN=25\n"
                        "vol=25\n"
                        "Key code constant: Power Key.\n"
                        "KEYCODE_POWER=26\n"
                        "power=26=pwr=26\n"
                        "Key code constant: Camera Key.\n"
                        "Used to launch a camera application or take pictures. \n"
                        "KEYCODE_CAMERA=27\n"
                        "camera=27\n"
                        "Key code constant: Clear Key.\n"
                        "KEYCODE_CLEAR=28\n"
                        "Key code constant: 'A' Key.\n"
                        "KEYCODE_A=29\n"
                        "Key code constant: 'B' Key.\n"
                        "KEYCODE_B=30\n"
                        "Key code constant: 'C' Key.\n"
                        "KEYCODE_C=31\n"
                        "Key code constant: 'D' Key.\n"
                        "KEYCODE_D=32\n"
                        "Key code constant: 'E' Key.\n"
                        "KEYCODE_E=33\n"
                        "Key code constant: 'F' Key.\n"
                        "KEYCODE_F=34\n"
                        "Key code constant: 'G' Key.\n"
                        "KEYCODE_G=35\n"
                        "Key code constant: 'H' Key.\n"
                        "KEYCODE_H=36\n"
                        "Key code constant: 'I' Key.\n"
                        "KEYCODE_I=37\n"
                        "Key code constant: 'J' Key.\n"
                        "KEYCODE_J=38\n"
                        "Key code constant: 'K' Key.\n"
                        "KEYCODE_K=39\n"
                        "Key code constant: 'L' Key.\n"
                        "KEYCODE_L=40\n"
                        "Key code constant: 'M' Key.\n"
                        "KEYCODE_M=41\n"
                        "Key code constant: 'N' Key.\n"
                        "KEYCODE_N=42\n"
                        "Key code constant: 'O' Key.\n"
                        "KEYCODE_O=43\n"
                        "Key code constant: 'P' Key.\n"
                        "KEYCODE_P=44\n"
                        "Key code constant: 'Q' Key.\n"
                        "KEYCODE_Q=45\n"
                        "Key code constant: 'R' Key.\n"
                        "KEYCODE_R=46\n"
                        "Key code constant: 'S' Key.\n"
                        "KEYCODE_S=47\n"
                        "Key code constant: 'T' Key.\n"
                        "KEYCODE_T=48\n"
                        "Key code constant: 'U' Key.\n"
                        "KEYCODE_U=49\n"
                        "Key code constant: 'V' Key.\n"
                        "KEYCODE_V=50\n"
                        "Key code constant: 'W' Key.\n"
                        "KEYCODE_W=51\n"
                        "Key code constant: 'X' Key.\n"
                        "KEYCODE_X=52\n"
                        "Key code constant: 'Y' Key.\n"
                        "KEYCODE_Y=53\n"
                        "Key code constant: 'Z' Key.\n"
                        "KEYCODE_Z=54\n"
                        "Key code constant: ',' Key.\n"
                        "KEYCODE_COMMA=55\n"
                        "Key code constant: '.' Key.\n"
                        "KEYCODE_PERIOD=56\n"
                        "Key code constant: Left Alt modifier Key.\n"
                        "KEYCODE_ALT_LEFT=57\n"
                        "Key code constant: Right Alt modifier Key.\n"
                        "KEYCODE_ALT_RIGHT=58\n"
                        "Key code constant: Left Shift modifier Key.\n"
                        "KEYCODE_SHIFT_LEFT\n" "59\n"
                        "Key code constant: Right Shift modifier Key.\n"
                        "KEYCODE_SHIFT_RIGHT=60\n"
                        "tab=61\n"
                        "Key code constant: Tab Key.\n"
                        "KEYCODE_TAB=61\n"
                        "Key code constant: Space Key.\n"
                        "KEYCODE_SPACE=62\n"
                        "space=62\n"
                        "spc=62\n"
                        "Key code constant: Symbol modifier Key.\n"
                        "Used to enter alternate symbols. \n"
                        "KEYCODE_SYM=63\n"
                        "Key code constant: Explorer special function Key.\n"
                        "Used to launch a browser application. \n"
                        "KEYCODE_EXPLORER=64\n"
                        "browser=64\n"
                        "Key code constant: Envelope special function Key.\n"
                        "Used to launch a mail application. \n"
                        "KEYCODE_ENVELOPE=65\n"
                        "Key code constant: Enter Key.\n"
                        "KEYCODE_ENTER=66\n"
                        "ent=66\n"
                        "Key code constant: Backspace Key.\n"
                        "Deletes characters before the insertion po#define, unlike KEYCODE_FORWARD_DEL. \n"
                        "KEYCODE_DEL=67\n"
                        "del=67\n"
                        "Key code constant: '`' (backtick) Key.\n"
                        "KEYCODE_GRAVE=68\n"
                        "Key code constant: '-'. \n"
                        "KEYCODE_MINUS=69\n"
                        "Key code constant: '\"' Key.\n"
                        "KEYCODE_EQUALS=70\n"
                        "Key code constant: '[' Key.\n"
                        "KEYCODE_LEFT_BRACKET\n" "71\n"
                        "Key code constant: ']' Key.\n"
                        "KEYCODE_RIGHT_BRACKET\n" "72\n"
                        "Key code constant: '\\' Key.\n"
                        "KEYCODE_BACKSLASH=73\n"
                        "Key code constant: '\"' Key.\n"
                        "KEYCODE_SEMICOLON=74\n"
                        "Key code constant: ''' (apostrophe) Key.\n"
                        "KEYCODE_APOSTROPHE=75\n"
                        "Key code constant: '/' Key.\n"
                        "KEYCODE_SLASH=76\n"
                        "Key code constant: '@' Key.\n"
                        "KEYCODE_AT=77\n"
                        "Key code constant: Number modifier Key.\n"
                        "Used to enter numeric symbols."
                        "This Key is not Num Lock it is more like KEYCODE_ALT_LEFT and is\n"
                        "#defineerpreted as an ALT Key by android.text.method.MetaKey.KeyListener. \n"
                        "KEYCODE_NUM=78\n"
                        "Key code constant: Headset Hook Key.\n"
                        "Used to hang up calls and stop media. \n"
                        "KEYCODE_HEADSETHOOK=79\n"
                        "Key code constant: Camera Focus Key.\n"
                        "Used to focus the camera. \n"
                        "KEYCODE_FOCUS=80\n"  // *Camera"focus
                        "Key code constant: '+' Key.\n"
                        "KEYCODE_PLUS=81\n"
                        "Key code constant: Menu Key.\n"
                        "KEYCODE_MENU=82\n"
                        "unlock=82\n"
                        "menu=82\n"
                        "Key code constant: Notification Key.\n"
                        "KEYCODE_NOTIFICATION\n" "83\n"
                        "systray\n" "83\n"
                        "Key code constant: Search Key.\n"
                        "KEYCODE_SEARCH=84\n"
                        "search=84\n"
                        "Key code constant: Play/Pause media Key.\n"
                        "KEYCODE_MEDIA_PLAY_PAUSE\n" "85\n"
                        "Key code constant: Stop media Key.\n"
                        "KEYCODE_MEDIA_STOP\n" "86\n"
                        "Key code constant: Play Next media Key.\n"
                        "KEYCODE_MEDIA_NEXT\n" "87\n"
                        "Key code constant: Play Previous media Key.\n"
                        "KEYCODE_MEDIA_PREVIOUS=88\n"
                        "Key code constant: Rewind media Key.\n"
                        "KEYCODE_MEDIA_REWIND\n" "89\n"
                        "Key code constant: Fast Forward media Key.\n"
                        "KEYCODE_MEDIA_FAST_FORWARD\n" "90\n"
                        "Key code constant: Mute Key.\n"
                        "Mutes the microphone, unlike KEYCODE_VOLUME_MUTE. \n"
                        "KEYCODE_MUTE=91\n"
                        "Key code constant: Page Up Key.\n"
                        "KEYCODE_PAGE_UP=92\n"
                        "Key code constant: Page Down Key.\n"
                        "KEYCODE_PAGE_DOWN=93\n"
                        "Key code constant: Picture Symbols modifier Key.\n"
                        "Used to switch symbol sets (Emoji, Kao-moji). \n"
                        "KEYCODE_PICTSYMBOLS=94"  // switch symbol-sets (Emoji,Kao-moji)
                        "Key code constant: Switch Charset modifier Key.\n"
                        "Used to switch character sets (Kanji, Katakana). \n"
                        "KEYCODE_SWITCH_CHARSET=95"  // switch char-sets (Kanji,Katakana)
                        "Key code constant: A Button Key.\n"
                        "On a game controller, the A button should be either the button labeled A"
                        "or the first button on the upper row of controller buttons. \n"
                        "KEYCODE_BUTTON_A=96\n"
                        "Key code constant: B Button Key.\n"
                        "On a game controller, the B button should be either the button labeled B"
                        "or the second button on the upper row of controller buttons. \n"
                        "KEYCODE_BUTTON_B=97\n"
                        "Key code constant: C Button Key.\n"
                        "On a game controller, the C button should be either the button labeled C"
                        "or the third button on the upper row of controller buttons. \n"
                        "KEYCODE_BUTTON_C=98\n"
                        "Key code constant: X Button Key.\n"
                        "On a game controller, the X button should be either the button labeled X"
                        "or the first button on the lower row of controller buttons. \n"
                        "KEYCODE_BUTTON_X=99\n"
                        "Key code constant: Y Button Key.\n"
                        "On a game controller, the Y button should be either the button labeled Y"
                        "or the second button on the lower row of controller buttons. \n"
                        "KEYCODE_BUTTON_Y=100\n"
                        "Key code constant: Z Button Key.\n"
                        "On a game controller, the Z button should be either the button labeled Z"
                        "or the third button on the lower row of controller buttons. \n"
                        "KEYCODE_BUTTON_Z=101\n"
                        "Key code constant: L1 Button Key.\n"
                        "On a game controller, the L1 button should be either the button labeled L1 (or L)"
                        "or the top left trigger button. \n"
                        "KEYCODE_BUTTON_L1=102\n"
                        "Key code constant: R1 Button Key.\n"
                        "On a game controller, the R1 button should be either the button labeled R1 (or R)"
                        "or the top right trigger button. \n"
                        "KEYCODE_BUTTON_R1=103\n"
                        "Key code constant: L2 Button Key.\n"
                        "On a game controller, the L2 button should be either the button labeled L2"
                        "or the bottom left trigger button. \n"
                        "KEYCODE_BUTTON_L2=104\n"
                        "Key code constant: R2 Button Key.\n"
                        "On a game controller, the R2 button should be either the button labeled R2"
                        "or the bottom right trigger button. \n"
                        "KEYCODE_BUTTON_R2=105\n"
                        "Key code constant: Left Thumb Button Key.\n"
                        "On a game controller, the left thumb button indicates that the left (or only)"
                        "joystick is pressed. \n"
                        "KEYCODE_BUTTON_THUMBL=106\n"
                        "Key code constant: Right Thumb Button Key.\n"
                        "On a game controller, the right thumb button indicates that the right"
                        "joystick is pressed. \n"
                        "KEYCODE_BUTTON_THUMBR=107\n"
                        "Key code constant: Start Button Key.\n"
                        "On a game controller, the button labeled Start. \n"
                        "KEYCODE_BUTTON_START\n" "108\n"
                        "Key code constant: Select Button Key.\n"
                        "On a game controller, the button labeled Select. \n"
                        "KEYCODE_BUTTON_SELECT=109\n"
                        "Key code constant: Mode Button Key.\n"
                        "On a game controller, the button labeled Mode. \n"
                        "KEYCODE_BUTTON_MODE=110\n"
                        "Key code constant: Escape Key.\n"
                        "KEYCODE_ESCAPE=111\n"
                        "escape=111\n"
                        "esc=111\n"
                        "Key code constant: Forward Delete Key.\n"
                        "Deletes characters ahead of the insertion unlike KEYCODE_DEL. \n"
                        "KEYCODE_FORWARD_DEL=112\n"
                        "Key code constant: Left Control modifier Key.\n"
                        "KEYCODE_CTRL_LEFT=113\n"
                        "Key code constant: Right Control modifier Key.\n"
                        "KEYCODE_CTRL_RIGHT\n" "114\n"
                        "Key code constant: Caps Lock Key.\n"
                        "KEYCODE_CAPS_LOCK=115\n"
                        "Key code constant: Scroll Lock Key.\n"
                        "KEYCODE_SCROLL_LOCK=116\n"
                        "Key code constant: Left Meta modifier Key.\n"
                        "KEYCODE_META_LEFT=117\n"
                        "Key code constant: Right Meta modifier Key.\n"
                        "KEYCODE_META_RIGHT=118\n"
                        "Key code constant: Function modifier Key.\n"
                        "KEYCODE_FUNCTION=119\n"
                        "Key code constant: System Request / PrScreen Key.\n"
                        "KEYCODE_SYSRQ=120\n"
                        "Key code constant: Break / Pause Key.\n"
                        "KEYCODE_BREAK=121\n"
                        "Key code constant: Home Movement Key.\n"
                        "Used for scrolling or moving the cursor around to the start of a line"
                        "or to the top of a list. \n"
                        "KEYCODE_MOVE_HOME=122\n"
                        "Key code constant: End Movement Key.\n"
                        "Used for scrolling or moving the cursor around to the end of a line"
                        "or to the bottom of a list. \n"
                        "KEYCODE_MOVE_END=123\n"
                        "Key code constant: Insert Key.\n"
                        "Toggles insert / overwrite edit mode. \n"
                        "KEYCODE_INSERT=124\n"
                        "Key code constant: Forward Key.\n"
                        "Navigates forward in the history stack.  Complement of KEYCODE_BACK. \n"
                        "KEYCODE_FORWARD=125\n"
                        "Key code constant: Play media Key.\n"
                        "KEYCODE_MEDIA_PLAY=126\n"
                        "Key code constant: Pause media Key.\n"
                        "KEYCODE_MEDIA_PAUSE=127\n"
                        "Key code constant: Close media Key.\n"
                        "May be used to close a CD tray, for example. \n"
                        "KEYCODE_MEDIA_CLOSE=128\n"
                        "Key code constant: Eject media Key.\n"
                        "May be used to eject a CD tray, for example. \n"
                        "KEYCODE_MEDIA_EJECT=129\n"
                        "Key code constant: Record media Key.\n"
                        "KEYCODE_MEDIA_RECORD=130\n"
                        "Key code constant: F1 Key.\n"
                        "KEYCODE_F1=131\n"
                        "Key code constant: F2 Key.\n"
                        "KEYCODE_F2=132\n"
                        "Key code constant: F3 Key.\n"
                        "KEYCODE_F3=133\n"
                        "Key code constant: F4 Key.\n"
                        "KEYCODE_F4=134\n"
                        "Key code constant: F5 Key.\n"
                        "KEYCODE_F5=135\n"
                        "Key code constant: F6 Key.\n"
                        "KEYCODE_F6=136\n"
                        "Key code constant: F7 Key.\n"
                        "KEYCODE_F7=137\n"
                        "Key code constant: F8 Key.\n"
                        "KEYCODE_F8=138\n"
                        "Key code constant: F9 Key.\n"
                        "KEYCODE_F9=139\n"
                        "Key code constant: F10 Key.\n"
                        "KEYCODE_F10=140\n"
                        "Key code constant: F11 Key.\n"
                        "KEYCODE_F11=141\n"
                        "Key code constant: F12 Key.\n"
                        "KEYCODE_F12=142\n"
                        "Key code constant: Num Lock Key.\n"
                        "This is the Num Lock Key it is different from KEYCODE_NUM.\n"
                        "This Key alters the behavior of other Keys on the numeric Keypad. \n"
                        "KEYCODE_NUM_LOCK=143\n"
                        "Key code constant: Numeric Keypad '0' Key.\n"
                        "KEYCODE_NUMPAD_0=144\n"
                        "Key code constant: Numeric Keypad '1' Key.\n"
                        "KEYCODE_NUMPAD_1=145\n"
                        "Key code constant: Numeric Keypad '2' Key.\n"
                        "KEYCODE_NUMPAD_2=146\n"
                        "Key code constant: Numeric Keypad '3' Key.\n"
                        "KEYCODE_NUMPAD_3=147\n"
                        "Key code constant: Numeric Keypad '4' Key.\n"
                        "KEYCODE_NUMPAD_4=148\n"
                        "Key code constant: Numeric Keypad '5' Key.\n"
                        "KEYCODE_NUMPAD_5=149\n"
                        "Key code constant: Numeric Keypad '6' Key.\n"
                        "KEYCODE_NUMPAD_6=150\n"
                        "Key code constant: Numeric Keypad '7' Key.\n"
                        "KEYCODE_NUMPAD_7=151\n"
                        "Key code constant: Numeric Keypad '8' Key.\n"
                        "KEYCODE_NUMPAD_8=152\n"
                        "Key code constant: Numeric Keypad '9' Key.\n"
                        "KEYCODE_NUMPAD_9=153\n"
                        "Key code constant: Numeric Keypad '/' Key (for division). \n"
                        "KEYCODE_NUMPAD_DIVIDE=154\n"
                        "Key code constant: Numeric Keypad '*' Key (for multiplication). \n"
                        "KEYCODE_NUMPAD_MULTIPLY=155\n"
                        "Key code constant: Numeric Keypad '-' Key (for subtraction). \n"
                        "KEYCODE_NUMPAD_SUBTRACT=156\n"
                        "Key code constant: Numeric Keypad '+' Key (for addition). \n"
                        "KEYCODE_NUMPAD_ADD=157\n"
                        "Key code constant: Numeric Keypad '.' Key (for decimals or digit grouping). \n"
                        "KEYCODE_NUMPAD_DOT=158\n"
                        "Key code constant: Numeric Keypad ',' Key (for decimals or digit grouping). \n"
                        "KEYCODE_NUMPAD_COMMA=159\n"
                        "Key code constant: Numeric Keypad Enter Key.\n"
                        "KEYCODE_NUMPAD_ENTER=160\n"
                        "Key code constant: Numeric Keypad '\"' Key.\n"
                        "KEYCODE_NUMPAD_EQUALS=161\n"
                        "Key code constant: Numeric Keypad '(' Key.\n"
                        "KEYCODE_NUMPAD_LEFT_PARENT=162\n"
                        "Key code constant: Numeric Keypad ')' Key.\n"
                        "KEYCODE_NUMPAD_RIGHT_PARENT=163\n"
                        "Key code constant: Volume Mute Key.\n"
                        "Mutes the speaker, unlike KEYCODE_MUTE}."
                        "This Key should normally be implemented as a toggle such that the first press"
                        "mutes the speaker and the second press restores the original volume. \n"
                        "KEYCODE_VOLUME_MUTE=164\n"
                        "Key code constant: Info Key.\n"
                        "Common on TV remotes to show additional information related to what is"
                        "currently being viewed. \n"
                        "KEYCODE_INFO=165\n"
                        "Key code constant: Channel up Key.\n"
                        "On TV remotes, increments the television channel. \n"
                        "KEYCODE_CHANNEL_UP\n" "166\n"
                        "Key code constant: Channel down Key.\n"
                        "On TV remotes, decrements the television channel. \n"
                        "KEYCODE_CHANNEL_DOWN\n" "167\n"
                        "Key code constant: Zoom in Key.\n"
                        "KEYCODE_ZOOM_IN=168\n"
                        "Key code constant: Zoom out Key.\n"
                        "KEYCODE_ZOOM_OUT=169\n"
                        "Key code constant: TV Key.\n"
                        "On TV remotes, switches to viewing live TV. \n"
                        "KEYCODE_TV=170\n"
                        "Key code constant: Window Key.\n"
                        "On TV remotes, toggles picture-in-picture mode or other windowing functions. \n"
                        "KEYCODE_WINDOW=171\n"
                        "Key code constant: Guide Key.\n"
                        "On TV remotes, shows a programming guide. \n"
                        "KEYCODE_GUIDE=172\n"
                        "Key code constant: DVR Key.\n"
                        "On some TV remotes, switches to a DVR mode for recorded shows. \n"
                        "KEYCODE_DVR=173\n"
                        "Key code constant: Bookmark Key.\n"
                        "On some TV remotes, bookmarks content or web pages. \n"
                        "KEYCODE_BOOKMARK=174\n"
                        "Key code constant: Toggle captions Key.\n"
                        "Switches the mode for closed-captioning text, for example during television shows. \n"
                        "KEYCODE_CAPTIONS=175\n"
                        "Key code constant: Settings Key.\n"
                        "Starts the system settings activity. \n"
                        "KEYCODE_SETTINGS=176\n"
                        "Key code constant: TV power Key.\n"
                        "On TV remotes, toggles the power on a television screen. \n"
                        "KEYCODE_TV_POWER=177\n"
                        "Key code constant: TV input Key.\n"
                        "On TV remotes, switches the input on a television screen. \n"
                        "KEYCODE_TV_INPUT=178\n"
                        "Key code constant: Set-top-box power Key.\n"
                        "On TV remotes, toggles the power on an external Set-top-box. \n"
                        "KEYCODE_STB_POWER=179\n"
                        "Key code constant: Set-top-box input Key.\n"
                        "On TV remotes, switches the input mode on an external Set-top-box. \n"
                        "KEYCODE_STB_INPUT=180\n"
                        "Key code constant: A/V Receiver power Key.\n"
                        "On TV remotes, toggles the power on an external A/V Receiver. \n"
                        "KEYCODE_AVR_POWER=181\n"
                        "Key code constant: A/V Receiver input Key.\n"
                        "On TV remotes, switches the input mode on an external A/V Receiver. \n"
                        "KEYCODE_AVR_INPUT=182\n"
                        "Key code constant: Red programmable=Key.\n"
                        "On TV remotes, acts as a contextual/programmable Key.\n"
                        "KEYCODE_PROG_RED=183\n"
                        "Key code constant: Green programmable=Key.\n"
                        "On TV remotes, actsas a contextual/programmable Key.\n"
                        "KEYCODE_PROG_GREEN\n" "184\n"
                        "Key code constant: Yellow programmable=Key.\n"
                        "On TV remotes, acts as a contextual/programmable Key.\n"
                        "KEYCODE_PROG_YELLOW=185\n"
                        "Key code constant: Blue programmable=Key.\n"
                        "On TV remotes, acts as a contextual/programmable Key.\n"
                        "KEYCODE_PROG_BLUE=186\n"
                        "Key code constant: App switch Key.\n"
                        "Should bring up the application switcher dialog. \n"
                        "KEYCODE_APP_SWITCH\n" "187\n"
                        "Key code constant: Generic Game Pad Button #1.\n"
                        "KEYCODE_BUTTON_1=188\n"
                        "Key code constant: Generic Game Pad Button #2.\n"
                        "KEYCODE_BUTTON_2=189\n"
                        "Key code constant: Generic Game Pad Button #3.\n"
                        "KEYCODE_BUTTON_3=190\n"
                        "Key code constant: Generic Game Pad Button #4.\n"
                        "KEYCODE_BUTTON_4=191\n"
                        "Key code constant: Generic Game Pad Button #5.\n"
                        "KEYCODE_BUTTON_5=192\n"
                        "Key code constant: Generic Game Pad Button #6.\n"
                        "KEYCODE_BUTTON_6=193\n"
                        "Key code constant: Generic Game Pad Button #7.\n"
                        "KEYCODE_BUTTON_7=194\n"
                        "Key code constant: Generic Game Pad Button #8.\n"
                        "KEYCODE_BUTTON_8=195\n"
                        "Key code constant: Generic Game Pad Button #9.\n"
                        "KEYCODE_BUTTON_9=196\n"
                        "Key code constant: Generic Game Pad Button #10.\n"
                        "KEYCODE_BUTTON_10=197\n"
                        "Key code constant: Generic Game Pad Button #11.\n"
                        "KEYCODE_BUTTON_11=198\n"
                        "Key code constant: Generic Game Pad Button #12.\n"
                        "KEYCODE_BUTTON_12=199\n"
                        "Key code constant: Generic Game Pad Button #13.\n"
                        "KEYCODE_BUTTON_13=200\n"
                        "Key code constant: Generic Game Pad Button #14.\n"
                        "KEYCODE_BUTTON_14=201\n"
                        "Key code constant: Generic Game Pad Button #15.\n"
                        "KEYCODE_BUTTON_15=202\n"
                        "Key code constant: Generic Game Pad Button #16.\n"
                        "KEYCODE_BUTTON_16=203\n"
                        "Key code constant: Language Switch Key.\n"
                        "Toggles the current input language such as switching between English and Japanese on"
                        "a QWERTY Keyboard.  On some devices, the same function may be performed by"
                        "pressing Shift+Spacebar. \n"
                        "KEYCODE_LANGUAGE_SWITCH=204\n"
                        "Key code constant: Manner Mode Key.\n"
                        "Toggles silent or vibrate mode on and off to make the device behave more politely"
                        "in certain settings such as on a crowded train.  On some devices, the Key may only\n"
                        "operate when long-pressed. \n"
                        "KEYCODE_MANNER_MODE=205\n"
                        "Key code constant: 3D Mode Key.\n"
                        "Toggles the display between 2D and 3D mode. \n"
                        "KEYCODE_3D_MODE=206\n"
                        "Key code constant: Contacts special function Key.\n"
                        "Used to launch an address book application. \n"
                        "KEYCODE_CONTACTS=207\n"
                        "Key code constant: Calendar special function Key.\n"
                        "Used to launch a calendar application. \n"
                        "KEYCODE_CALENDAR=208\n"
                        "Key code constant: Music special function Key.\n"
                        "Used to launch a music player application. \n"
                        "KEYCODE_MUSIC=209\n"
                        "Key code constant: Calculator special function Key.\n"
                        "Used to launch a calculator application. \n"
                        "KEYCODE_CALCULATOR=210\n");

}

